### PR TITLE
Add support for fprintf_usage and typo fixes

### PR DESCRIPTION
**Pull request by xexyl**
Since commit https://github.com/ioccc-src/mkiocccentry/commit/6ed22cc2e620688dd8c3e9e7d7d864d796f20d9b on the mkiocccentry repo the function used throughout the files is `fprintf_usage()` but the tool only had `vprintf_usage()`.

I also fixed some typos and (if this is not desired feel free to roll it back) changed non-standard spelling `thru` to `through`.

### CODE REVIEW

**Comment by lcn2** [comment]
Thanks ... will update the other repo as well.

**Comment by xexyl** [comment]
> Thanks @xexyl

Happy to help! Going to sleep now. Hope you have a great night! I am feeling much better today so tomorrow I should be all well in that way. 

Good night!

**Comment by lcn2** [comment]
> > Thanks @xexyl
> 
> Happy to help! Going to sleep now. Hope you have a great night! I am feeling much better today so tomorrow I should be all well in that way.
> 
> Good night!

That is good news no feeling better ..

.. didn't have much time to work on things today .. perhaps later on.

**Comment by xexyl** [comment]
> > > Thanks @xexyl
> > 
> > 
> > Happy to help! Going to sleep now. Hope you have a great night! I am feeling much better today so tomorrow I should be all well in that way.
> > Good night!
> 
> That is good news no feeling better ..
> 

Thank you!

> .. didn't have much time to work on things today .. perhaps later on.

Yeah. We shall see I guess. But I hope you don’t deprive yourself of sleep. Well you know your body anyway. Good night!

**Comment by lcn2** [comment]
> > > > Thanks @xexyl
> > > 
> > > 
> > > Happy to help! Going to sleep now. Hope you have a great night! I am feeling much better today so tomorrow I should be all well in that way.
> > > Good night!
> > 
> > 
> > That is good news no feeling better ..
> 
> Thank you!
> 
> > .. didn't have much time to work on things today .. perhaps later on.
> 
> Yeah. We shall see I guess. But I hope you don’t deprive yourself of sleep. Well you know your body anyway. Good night!

Tonight won't be very long work session.  Best wishes.

**Comment by xexyl** [comment]
> > > > > Thanks @xexyl
> > > > 
> > > > 
> > > > Happy to help! Going to sleep now. Hope you have a great night! I am feeling much better today so tomorrow I should be all well in that way.
> > > > Good night!
> > > 
> > > 
> > > That is good news no feeling better ..
> > 
> > 
> > Thank you!
> > > .. didn't have much time to work on things today .. perhaps later on.
> > 
> > 
> > Yeah. We shall see I guess. But I hope you don’t deprive yourself of sleep. Well you know your body anyway. Good night!
> 
> Tonight won't be very long work session. Best wishes.

That's good. Hope you're having a nice sleep my friend! Still waking up but with that problem of can't sleep but can't wake up either - yet. I'll reply to the other things in a bit.

**Comment by lcn2** [comment]
Lost internet connection in our general region. May be a while before we get back.

**Comment by xexyl** [comment]
Good luck!

**Pull request merged**
